// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "lmosactxctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CLmosactxctrl1

IMPLEMENT_DYNCREATE(CLmosactxctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLmosactxctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CLmosactxctrl1 operations
