---
name: C/C++ Makefile CI - amd64

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: gentoo-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: "${{ secrets.CLONE_TOKEN }}"

      - name: Set environment variables
        run: |
          echo "WS_TIMEOUT_SHORT=1000" >> ${GITHUB_ENV}
          echo "WS_SERVER_TEST=ws://127.0.0.1:7890" >> ${GITHUB_ENV}
      - name: Compile release build
        run: |
          make clean
          make release
      - name: Run unit tests
        run: make unit_tests
      - name: Run system tests
        run: make system_tests

      - name: Build all targets
        run: make alltargetscheck

      - name: Send a Telegram message on failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
        if: ${{ failure() }}
...
