.TH BLASTPIT 1
.SH NAME
blastpit \- Server for Rofin EasyJewel laser system
.SH SYNOPSIS
.B blastpit
.SH DESCRIPTION
.B blastpit
is a network server that allows remote control of the Rofin EasyJewel laser system. It has bindings for the Python language, as well as helper functions
.SH NOTES
.SH BUGS
blastpit relies on the Rofin LMOS ActiveX control for its functionality. Currently, several features are unavailable from the LMOS control, which limit. These include
.SH EXAMPLE
