all:

clean:
	rm -f doc/manual/*.{aux,idx,log,ptc,toc,ilg,ind}
	rm -f doc/tex/*.{aux,idx,log,ptc,toc,ilg,ind}
	rm -f doc/tex/faq.{faq,out,pdf} doc/manual/manual.pdf doc/tex/snip.pdf
	rm -f doc/man/man3/_home*

test:
	/bin/true
