######################################################################
# Automatically generated by qmake (3.1) Sat Jul 21 20:07:15 2018
######################################################################

TEMPLATE = app
TARGET = blastpit_test

QT += testlib core network

INCLUDEPATH += .
INCLUDEPATH += ../../libblastpit

HEADERS += \
	blastpit_test.h

SOURCES += \
	blastpit_test.cpp

LIBS += -L$$OUT_PWD/../../libblastpit -lblastpit

# We need to hard-code the path into libblastpit (during development)
QMAKE_LFLAGS += -Wl,-rpath=$$OUT_PWD/../../libblastpit
